### ISSUE TITLE
cnocr不能使用

### ISSUE THREAD

**Issue by xiajunwen1007** [Chandler-Lu/alfred-ocr#12]
cncor运行时出现如下错误
![image](https://user-images.githubusercontent.com/49160447/120450912-7e4dd080-c3c3-11eb-8e75-a18b4ae32750.png)

**Comment by Chandler-Lu** [comment]
您好，python 3.8.5 测试通过，python 3.9 可能存在某些兼容问题。这个应该是 cnocr 和 mxnet 那边的兼容性问题了。

**Comment by xiajunwen1007** [comment]
感谢回复，这个功能用的也比较少。多谢开发者的脚本，非常好用。
