### ISSUE TITLE
使用cncor得到的是textscoreposition textscoreposition textscoreposition

### ISSUE THREAD

**Issue by est7** [Chandler-Lu/alfred-ocr#14]
之前是好用的，mac 自从12.3后不再提供pyhton2.7，自己用python3跑了下不管怎么截图得到的都是数个 textscoreposition 这三个在cnocr里面正好是OcrResult的三个参数，不知道怎么没正确返回

**Comment by Chandler-Lu** [comment]
不好意思我现在没有 mac 可以帮您测试，我的这个项目本身就是提供给 py3 使用的，所以应该不会有问题。
我在 windows 下，Python 3.7.11，cnocr 2.1.2.1 测试正常。可能没有办法帮到您

**Comment by codebysandwich** [comment]
@est7 

应该是cncor的版本问题。我的cnocr版本2.2.1，python版本3.8，自己测试后可以试试以下的方法：
将workflow包里的ocr.py中的cnocr_ocr方法做如下修改

```python
def cnocr_ocr(pic_path):
    from cnocr import CnOcr
    ocr = CnOcr()
    res = ocr.ocr(pic_path)
    for val in res:
        print(val['text'])
```

**Comment by Chandler-Lu** [comment]
非常感谢提供方案，可能是cnocr新版的输出又改了emmm

On Aug 22, 2022, at 14:45, sandwich ***@***.***> wrote:

﻿

@est7<https://github.com/est7>

应该是cncor的版本问题。我的cnocr版本2.2.1，python版本3.8，自己测试后可以试试以下的方法：
将workflow包里的ocr.py中的cnocr_ocr方法做如下修改

def cnocr_ocr(pic_path):
    from cnocr import CnOcr
    ocr = CnOcr()
    res = ocr.ocr(pic_path)
    for val in res:
        print(val['text'])

**Comment by est7** [comment]
@codebysandwich 谢谢，不太熟悉py语法，自己当时试了试没写对，现在复制你的搞好了
