### ISSUE TITLE
最新的mac Monterey好像用不了

### ISSUE THREAD

**Issue by ableno** [Chandler-Lu/alfred-ocr#15]
扫描后，出现invalid parameter

**Comment by Chandler-Lu** [comment]
您好，提供的信息太少了，没有办法排除问题

**Comment by rhapsody1290** [comment]
我看了源码成功了
1、进入百度
https://console.bce.baidu.com/ai/?_=1597892791979#/ai/ocr/overview/index
![image](https://user-images.githubusercontent.com/10919771/193850563-4d67d119-7715-4e2d-8d08-b48e3bbcb214.png)
2、领取：通用文字识别（标准含位置版）
3、创建应用，获得个人的appkey和secret
![image](https://user-images.githubusercontent.com/10919771/193850768-e17d538e-3085-4e7d-9a2b-702dbd48d199.png)
4、更新环境变量
![image](https://user-images.githubusercontent.com/10919771/193850926-e9dcdce9-61bb-486c-b5d4-8a7e04f56ae0.png)
![image](https://user-images.githubusercontent.com/10919771/193851052-afc4935a-9146-4124-80f0-bf3a8f90709c.png)
5、重启应用即可
