### ISSUE TITLE
按教程操作后 ctrl+V，后提示 NO premission to access data; (百度已更新)

### ISSUE THREAD

**Issue by yangbisheng** [Chandler-Lu/alfred-ocr#18]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/49109198/198523845-149fa67b-65df-4e4a-8aa4-2ff2ca3d0edd.png">

**Comment by Chandler-Lu** [comment]
您好，我内置的API已经弃用了（https://github.com/Chandler-Lu/alfred-ocr/wiki#%E5%85%B3%E4%BA%8E%E6%BB%A5%E7%94%A8）

**Comment by Chandler-Lu** [comment]
![image](https://user-images.githubusercontent.com/18322610/198532899-a2639ba5-c81d-448e-9de9-771c6204462d.png)
不好意思，没看到您已经更新百度api了，需要确认一下这部分接口是不是开通了

**Comment by yangbisheng** [comment]
我没有开通这部分，谢谢作者解答。
