### ISSUE TITLE
请问是否可以加入百度的表格文字识别（异步接口）

### ISSUE THREAD

**Issue by Moumilang** [Chandler-Lu/alfred-ocr#2]
请问是否可以加入百度的表格文字识别（异步接口）
https://ai.baidu.com/ai-doc/OCR/Ik3h7y238
我是小白，折腾半天，就是报图片格式错误，但是通用识别就没有报错。调试发现确实能返回base64的图片string。无能为力啊。。。

**Comment by Chandler-Lu** [comment]
好，晚些我来看看，可能需要点时间研究一下～

**Comment by Chandler-Lu** [comment]
做是做出来了，但是还有很多问题没有解决，可以先测试一下。
没有解决的问题如下：
1. 输出没有优化，比如第一个英文字母前会被加空格；
2. 多表格识别有些问题，测试了好几张图，明明同一张图里有2个以上表格，最后百度返回的依然是一个表，我也不清楚怎么回事，后续再测试一下
3. 可能会有一些异常的输出，多一个制表符或者多一个回车

目前还是个半成品～
