### ISSUE TITLE
调用baidu接口失败

### ISSUE THREAD

**Issue by Austin-Jack** [Chandler-Lu/alfred-ocr#20]
![image](https://user-images.githubusercontent.com/72635043/232179865-00b3473d-be6b-4abc-b3db-a317c84f9662.png)

**Comment by Austin-Jack** [comment]
我自己申请的百度API不能，另外申请的腾讯的没问题可以正常使用

**Comment by Chandler-Lu** [comment]
需要将源码替换为最新的版本 https://github.com/Chandler-Lu/alfred-ocr/tree/master/src ，因为没有 macOS 设备所以无法直接打包

**Comment by Austin-Jack** [comment]
> 需要将源码替换为最新的版本 https://github.com/Chandler-Lu/alfred-ocr/tree/master/src ，因为没有 macOS 设备所以无法直接打包

替换为最新的了，又出现新问题了。。
<img width="833" alt="image" src="https://user-images.githubusercontent.com/72635043/232180218-7604d5a1-e682-461f-aa54-a75e98173686.png">

**Comment by Chandler-Lu** [comment]
你的`API Key`填错了

**Comment by Austin-Jack** [comment]
我是直接复制过来的
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/72635043/232180543-4048b496-91d0-4299-a31a-1dc3c85f9808.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/72635043/232180561-77276a56-4936-468d-b267-eab126642896.png">

**Comment by Austin-Jack** [comment]
我是直接copy过来的，是这APIKey吧
![image](https://user-images.githubusercontent.com/72635043/232180606-ae849f82-4f7b-4724-b4c7-2d58a667296a.png)
<img width="889" alt="image" src="https://user-images.githubusercontent.com/72635043/232180636-37a1b8bf-d9da-4190-ae5d-4ac9c8b0891b.png">

**Comment by Austin-Jack** [comment]
不好意思我用的这个是账户APIKey，应该用应用的APIKey，现在调好了，感谢！
