### ISSUE TITLE
调用baidu Ocr没有权限访问data

### ISSUE THREAD

**Issue by Austin-Jack** [Chandler-Lu/alfred-ocr#21]
大佬又是我，现在的问题是他没有访问权限，不清楚是没有权限访问图片（失败了会把图片删除掉）还是配置文件，另外Tencent orc使用没有问题
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/72635043/232191778-05bb1164-7d9f-4649-9d83-74ddd34a2241.png">

**Comment by Chandler-Lu** [comment]
![image](https://user-images.githubusercontent.com/18322610/232192918-15324369-b3a4-47ec-b837-9a9a1648a467.png)
你创建的新应用没有开通这些接口权限

**Comment by Austin-Jack** [comment]
奥奥，可以了！我只开通了标准版所以只开了那个权限，然后在代码看到的接口是general结尾的，而我却只有general_basic，然后想来还有可以识别Excel这样的功能是需要带位置的识别的所以需要general接口，总之，现在终于跑通了，感谢大佬！！
