### ISSUE TITLE
最新版本，出现了SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by HomelandScenery** [Chandler-Lu/alfred-ocr#23]
大佬好，我是MacOS用户，已经升级到最新的版本4.9.5，截图后识别，不管是ooc，还是oob，都出现的错误，请问能否解决？谢谢
![Snipaste_2023-09-10_22-04-18](https://github.com/Chandler-Lu/alfred-ocr/assets/19407813/8cce4550-cc88-4c13-ae4b-9176df6ac307)

**Comment by Chandler-Lu** [comment]
您的python版本是不是有问题
________________________________
发件人: 故乡风月 ***@***.***>
发送时间: Sunday, September 10, 2023 10:05:10 PM
收件人: Chandler-Lu/alfred-ocr ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Chandler-Lu/alfred-ocr] 最新版本，出现了SyntaxError: invalid syntax (Issue #23)


大佬好，我是MacOS用户，已经升级到最新的版本4.9.5，截图后识别，不管是ooc，还是oob，都出现的错误，请问能否解决？谢谢
[Snipaste_2023-09-10_22-04-18]<https://user-images.githubusercontent.com/19407813/266840700-8cce4550-cc88-4c13-ae4b-9176df6ac307.jpg>

―

**Comment by HomelandScenery** [comment]
是的，我错了😃我应该写`/usr/local/bin/python3`才对。
另外，更新了百度的API Key，终于成功了，感谢大佬！
