### ISSUE TITLE
安装失败问题

### ISSUE THREAD

**Issue by LucasZhan** [Chandler-Lu/alfred-ocr#5]
你好，安装过程中出现error。 并且按照流程走完安装教程后ctrl+v无反应。 
下面是安装过程中出现的error截图
<img width="610" alt="Screen Shot 2020-03-27 at 10 57 23 pm" src="https://user-images.githubusercontent.com/41333680/77756747-b3ec8080-707f-11ea-9172-d54b6b160e3c.png">
接下来是使用关键词‘oob’触发的调试日志
[23:05:33.398] Capture then OCR[Keyword] Processing complete
[23:05:33.400] Capture then OCR[Keyword] Passing output '' to Arg and Vars
[23:05:33.400] Capture then OCR[Arg and Vars] Processing complete
[23:05:33.401] Capture then OCR[Arg and Vars] Passing output '' to Run Script
[23:05:33.496] ERROR: Capture then OCR[Run Script] pngpaste: No image data found on the clipboard, or could not convert!
[23:05:33.497] Capture then OCR[Run Script] Processing complete
[23:05:33.497] Capture then OCR[Run Script] Passing output '' to Run Script
[23:05:33.925] ERROR: Capture then OCR[Run Script] ./ocr.py:294: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (which_api is 'tencent_youtu_ocr'):
./ocr.py:300: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif (which_api is 'google_ocr'):
./ocr.py:304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif (which_api is 'baidu_qrcode'):
./ocr.py:360: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if chinese_tag is 1:
./ocr.py:436: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (is_line_spacing_check is 1) and (index != response_json['words_result_num'] - 1) and (response_json['words_result'][index + 1]['location']['top'] - response_json['words_result'][index]['location']['top'] > top_half + c.BAIDU_OCR_SPACING_OFFSET):
./ocr.py:438: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif (is_line_spacing_check is 0) and (index != response_json['words_result_num'] - 1) and (response_json['words_result'][index]['location']['width'] < width_half - c.BAIDU_OCR_WIDTH_OFFSET):
Traceback (most recent call last):
  File "./ocr.py", line 480, in <module>
    baidu_ocr(pic_path)
  File "./ocr.py", line 84, in baidu_ocr
    if (os.path.getsize(pic_path) <= 4194304):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ocr_screenshot.png'
[23:05:33.937] Capture then OCR[Run Script] Processing complete
[23:05:33.938] Capture then OCR[Run Script] Passing output '' to Post Notification

**Comment by Chandler-Lu** [comment]
cnocr的符合要求的mxnet依赖从库里被删掉了（https://github.com/breezedeus/cnocr/issues/36#issuecomment-599593765）

如果你不需要离线识别可以不装，在线ocr只依赖request

cnocr的问题要等原作者解决了

**Comment by LucasZhan** [comment]
> cnocr的符合要求的mxnet依赖从库里被删掉了（[https://github.com/breezedeus/cnocr/issues/36#issuecomment-599593765）](https://github.com/breezedeus/cnocr/issues/36#issuecomment-599593765%EF%BC%89)
> 
> 如果你不需要离线识别可以不装，在线ocr只依赖requests
> 
> cnocr的问题要等原作者解决了
requests已经安装
但ctrl+v依然无法调出截图框
使用oob关键字也无法现在识别

**Comment by LucasZhan** [comment]
> cnocr的符合要求的mxnet依赖从库里被删掉了（[https://github.com/breezedeus/cnocr/issues/36#issuecomment-599593765）](https://github.com/breezedeus/cnocr/issues/36#issuecomment-599593765%EF%BC%89)
> 
> 如果你不需要离线识别可以不装，在线ocr只依赖requests
> 
> cnocr的问题要等原作者解决了

requests已经安装
但ctrl+v依然无法调出截图框
使用oob关键字也无法现在识别

**Comment by Chandler-Lu** [comment]
稍等，了解了。3.8的python我需要查一下，我这边3.7.7无法复现

**Comment by LucasZhan** [comment]
> 稍等，了解了。3.8的python我需要查一下，我这边3.7.7无法复现

非常感谢

**Comment by Chandler-Lu** [comment]
您好，已经发布新版本，可以测试一下。用了一个不规范的语法在3.8不被支持了
https://cloud.yeslu.cn/github/Capture%20then%20OCR.zip

**Comment by LucasZhan** [comment]
您好。 4.4版本ctrl+v依然无法调出截图框 
使用oob/oot关键字也无法现在识别，均返回下图结果
<img width="388" alt="Screen Shot 2020-03-27 at 11 34 25 pm" src="https://user-images.githubusercontent.com/41333680/77758863-a5a06380-7083-11ea-8a37-d2f4e7c47dce.png">

**Comment by Chandler-Lu** [comment]
能否帮忙测试在终端是否可以执行 `screencapture -sx /tmp/ocr_screenshot.png`，因为调截图框是用的系统命令，并非我写的程序所为。
另外冒昧问一下，您用的不是管理员账户吗？

**Comment by LucasZhan** [comment]
您好。 terminal可以执行”screencapture -sx /tmp/ocr_screenshot.png“ 我用的也是管理员账户。

**Comment by Chandler-Lu** [comment]
方便加我微信私聊一下吗？微信：tuzi970503或者qq：359574212

**Comment by LucasZhan** [comment]
> tuzi970503

已经加了您微信了
