### ISSUE TITLE
关于升级到4.6后产生“file error!“”

### ISSUE THREAD

**Issue by meishiwanwan** [Chandler-Lu/alfred-ocr#6]
更新后快捷键可激活调用使用
通过“oo”激活提示“file error!“”
同时也无法调用其他如oof,ooe等

CNOCR 已经更新到v1.1.1

**Comment by Chandler-Lu** [comment]
我傻了，我完全忘了我还做了批量文件识别这个功能。。

一个一个回答吧。
1. oo的触发逻辑改为和oot, oob一致了，就是先用系统截图截图到剪贴板，然后再用oo触发。不像以前输入oo以后触发截图框了。这个功能我目前测试是正常的；
2. oof无法调用的问题是我代码写错了，已经修复；
3. ooe的表格识别，大部分情况是没问题的，但是因为百度的表格识别并不是很准，经常返回的数据就有问题，自然程序处理就有问题了。目前还在找解决方案。

**Comment by meishiwanwan** [comment]
> 我傻了，我完全忘了我还做了批量文件识别这个功能。。
> 
> 一个一个回答吧。
> 
> 1. oo的触发逻辑改为和oot, oob一致了，就是先用系统截图截图到剪贴板，然后再用oo触发。不像以前输入oo以后触发截图框了。这个功能我目前测试是正常的；
> 2. oof无法调用的问题是我代码写错了，已经修复；
> 3. ooe的表格识别，大部分情况是没问题的，但是因为百度的表格识别并不是很准，经常返回的数据就有问题，自然程序处理就有问题了。目前还在找解决方案。

是的，我也试出来了，通过截图可以后在激活oo触发可行，但是没有原来的oo截图框好用，因为mac装了其他的截图软件，每次截图都会自动在指定文件夹保存，所以体验上不是很好，但是不是大问题

还有个问题或者是建议，在翻译那里是否可以增加其他的翻译选择，比如google或者有道之类的，
最后就是对于长句子的翻译，一行的展示不全，只有粘贴出来才可以，有没有办法直接在alfred里显示长句的完整翻译结果呢？

**Comment by Chandler-Lu** [comment]
之所以改掉这个oo触发截图框逻辑是因为之前挺多人反馈这个逻辑很反人类。。要先用键盘输入字母，然后操作鼠标截图，再回到键盘进一步操作。
您可以手动修改如下连接方式回复原来的方案：
![Snipaste_2020-04-25_00-28-07](https://user-images.githubusercontent.com/18322610/80235165-ec39ab80-868b-11ea-8848-1533a5a3aaa2.png)

翻译接口近期可能不会新增了，因为主要的OCR还有很多地方没有完善

长句翻译没有办法显示全

如果对翻译方面有较高要求的话，可以考虑一下这个：https://github.com/ripperhe/Bob

**Comment by meishiwanwan** [comment]
> 之所以改掉这个oo触发截图框逻辑是因为之前挺多人反馈这个逻辑很反人类。。要先用键盘输入字母，然后操作鼠标截图，再回到键盘进一步操作。
> 您可以手动修改如下连接方式回复原来的方案：
> ![Snipaste_2020-04-25_00-28-07](https://user-images.githubusercontent.com/18322610/80235165-ec39ab80-868b-11ea-8848-1533a5a3aaa2.png)
> 
> 翻译接口近期可能不会新增了，因为主要的OCR还有很多地方没有完善
> 
> 长句翻译没有办法显示全
> 
> 如果对翻译方面有较高要求的话，可以考虑一下这个：https://github.com/ripperhe/Bob

感谢，收到，已更新最新版，oof已经解决
