### ISSUE TITLE
alfred3提示不兼容

### ISSUE THREAD

**Issue by wweggplant** [Chandler-Lu/alfred-ocr#7]
![图片](https://user-images.githubusercontent.com/4509523/81761058-7fcc0280-94fb-11ea-8590-abfe790f1c04.png)

**Comment by Chandler-Lu** [comment]
请问版本号是？

________________________________
发件人: wweggplant <notifications@github.com>
发送时间: Wednesday, May 13, 2020 9:24:34 AM
收件人: Chandler-Lu/alfred-ocr <alfred-ocr@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Chandler-Lu/alfred-ocr] alfred3提示不兼容 (#7)


[图片]<https://user-images.githubusercontent.com/4509523/81761058-7fcc0280-94fb-11ea-8590-abfe790f1c04.png>

―

**Comment by wweggplant** [comment]
@Chandler-Lu  v3.6[903]

**Comment by Chandler-Lu** [comment]
我要是没有记错的话，即使不付费升级到4，v3也应当可以升级到最后一版，应该是3.8.x
