### ISSUE TITLE
[Feature Request] 希望能支持Mathpix API来实现公式识别

### ISSUE THREAD

**Issue by RicardoMing** [Chandler-Lu/alfred-ocr#8]
Mathpix提供一个API可以识别图片中的公式，并转换成相应的LaTeX代码：

https://docs.mathpix.com/?python#process-image-v3-text

**Comment by Chandler-Lu** [comment]
看起来好像可以搞，我刚去申请了一个API key，等等回信看看啥情况，我还真没申请过，一直在用官方的那个客户端，因为还可以当 latex 的公式编辑器用233

**Comment by RicardoMing** [comment]
客户端每个月有5次免费，API的话是1000次

**Comment by Chandler-Lu** [comment]
就很诡异，我周末回了他邮件之后就再也没回我了，不知道咋回事😂

**Comment by RicardoMing** [comment]
我刚才试了一下，直接在 https://accounts.mathpix.com/signup?return_to=/ocr-api 注册账号，然后添加付款信息就可以使用API了：
![image](https://user-images.githubusercontent.com/11895323/87537764-bfff5b00-c6cd-11ea-9331-02819c5f03fa.png)

**Comment by Chandler-Lu** [comment]
完工～就是识别速度有点慢，不知道是国内网络问题还是我这里的网络问题，我用客户端倒是没有这么慢。

原图：
![CleanShot 2020-07-15 at 21 21 33](https://user-images.githubusercontent.com/18322610/87550085-3e192d00-c6e1-11ea-9174-6e8ae7170388.png)

输出：
`\mathrm{e}^{-\frac{1}{2} \cdot x}\left(a \sin \frac{\sqrt{3}}{2} x+b x \cos \frac{\sqrt{3}}{2} x\right)`

Latex 转换后：
![image](https://user-images.githubusercontent.com/18322610/87550332-83d5f580-c6e1-11ea-9012-e643ec2f639e.png)

**Comment by RicardoMing** [comment]
可能是网络问题，我这边测试识别基本是1s左右
